### ISSUE TITLE
No provided shell script in "challenge" folder

### ISSUE THREAD

**Issue by MYPei** [edbennett/publishing-analysis#12]
Page: https://edbennett.github.io/publishing-analysis/05-data/index.html

Issue: The last challenge with `curl` refers to a shell script to be used with the downloaded csv, but no shell script is provided in the directory. Can either provide a pre-written script or add writing the script as part of the challenge to resolve.

**Comment by edbennett** [comment]
Turns out this was part of the challenge in episode 03, we just skipped over it. I've adjusted it to make this more obvious. Hopefully fixing #13 will help here too.
