### ISSUE TITLE
Teaching user account issues with conda create

### ISSUE THREAD

**Issue by MYPei** [edbennett/publishing-analysis#14]
Page: https://edbennett.github.io/publishing-analysis/06-environments/index.html

Issue: environment creation with `conda create` runs into issues when running on teaching account shell due to lack of write permissions. Swap to different user account to demonstrate or adjust teaching account permissions.

**Comment by edbennett** [comment]
This is specific to the setup on my machine—I don't think it's a problem with the material. Perhaps something could be in the instructor notes.
