### ISSUE TITLE
GitHub releases to Zenodo require manual tagging

### ISSUE THREAD

**Issue by MYPei** [edbennett/publishing-analysis#16]
Page: https://edbennett.github.io/publishing-analysis/08-pushing/index.html

Issue: In section on publishing GitHub repositories to Zenodo sandbox, the segment on creating a release requires a tag, which GitHub does not automatically generate. Will need to include a short tutorial on manual tagging in the command line.

**Comment by edbennett** [comment]
Turns out you don't need to use the command line; just the UI is terrible so doesn't tell you you need to type a name for the tag in the on the web form. Will add a sentence explaining this.
