### ISSUE TITLE
Public .gitignore templates

### ISSUE THREAD

**Issue by fjebaker** [edbennett/publishing-analysis#18]
I think this course could be improved by mentioning where one can find public `.gitignore` templates for different languages -- specifically the [github/gitignore repository](https://github.com/github/gitignore).  

These have a number of benefits:
- help avoid accidentally committing files that shouldn't be committed,
- are continuously updated to latest available language specifications,
- are the product of standardised consensus of what should and should not be committed (e.g., package lock files); and
- for the curious, provides a means of finding new tools (as common tools are included in these `.gitignore` files).

**Comment by edbennett** [comment]
Thanks @fjebaker, that's a really good idea. I'll try and add something into the first episode.
