### ISSUE TITLE
mention git hooks

### ISSUE THREAD

**Issue by colinsauze** [edbennett/publishing-analysis#23]
It would be useful to cover git hooks/filters before the nbstripout section so that we can cover running nbstripout upon git commit.

**Comment by edbennett** [comment]
I feel like explaining the entire mechanism of git hooks/filters is overkill to understand that "once you have run `nbstripout --install` it attaches itself to your local copy and automatically filters when you add/commit a notebook"? As I mentioned in another issue, we're already quite concept-heavy in this lesson, so I think it makes sense to gloss over some of the technical foundation of the tooling.

I guess this could be (yet) another callout?
