### ISSUE TITLE
Non-python includes in environment

### ISSUE THREAD

**Issue by chillenzer** [edbennett/publishing-analysis#28]
Maybe one should include `curl` into the conda environment just for the sake of showcasing how one could have missed that.

**Comment by edbennett** [comment]
Good idea—in principle all OSes should already have `curl` installed, but as a way of a) demonstrating for other tools that might not be on all platforms, and b) getting a consistent version (e.g. `Make` is old on macOS, and `sed` is BSD instead of GNU so has slightly different options)
