### ISSUE TITLE
2nd page typo collection

### ISSUE THREAD

**Issue by MYPei** [edbennett/publishing-analysis#3]
Page: https://edbennett.github.io/publishing-analysis/02-file-structure/index.html

Issue: `git add README` should be `git add README.txt` in 1st instance, `git add LICENSE` in 2nd instance, `git add CITATION` in 3rd instance. Should LICENSE and CITATION be .txt?

In `Directory structure` section, `git push` should be `git push origin main`.

**Comment by edbennett** [comment]
Thanks Michael; I think I'm happy leaving the LICENSE and CITATION without an extension.
