### ISSUE TITLE
make sure input files are in the data directory

### ISSUE THREAD

**Issue by mmesiti** [edbennett/publishing-analysis#6]
In the previous episode frankenstein.txt has been moved to `data`.
This episode should be consistent with that 
(possibly not only the shell snippet in the 'Use a shell script' section,
but also the `countwords.py` script?)

Edit: referring to episode 3 - Documentation and automation.

**Comment by edbennett** [comment]
Yes, probably episode 2 should have a short section where the script is edited to point at the correct location (while pointing out that in the next section we'll rip out the hardcoded filename anyway).
